#!/usr/bin/env bash
set -e

main() {
  local apt=(
    "build-essential" "zlib1g-dev" "libxml2-dev"
    "libxslt1-dev" "libssl-dev" "libbz2-dev"
    "libreadline-dev" "libsqlite3-dev" "libffi-dev"
  )
  local pip2=( "neovim" )
  local pip3=( "neovim" )
  local npm=( "neovim" )
  local gem=( "neovim" )

  install_apt "${apt[@]}"
  # install_brew
  install_asdf
  install pip2 "${pip2[@]}"
  install pip3 "${pip3[@]}"
  install "npm -g" "${npm[@]}"
  install gem "${gem[@]}"
  install_nvim
}

install_apt() {
  if [[ $(__os_type) == 'Ubuntu' ]]; then
    __inf "Initializing apt packages."
    sudo apt-get update
    sudo apt-get install "$@"
  fi
}

install_brew() {
  __inf "Initializing brew packages."
  command brew bundle --global
}

install_asdf() {
  __inf "Initializing ASDF plugins."
  plugins="$(cat ~/.tool-versions | awk '{print $1}')"

  set +e
  for plugin in $plugins; do
    command asdf plugin add $plugin
    if [[ $plugin == nodejs ]]; then
      bash -c "$(__asdf_data_dir)/plugins/nodejs/bin/import-release-team-keyring"
    fi
  done
  set -e

  __inf "Installing ASDF plugins."
  command asdf install
}

install_nvim() {
  __inf "Initializing vim plugins."
  command nvim +PlugInstall +qall
  command nvim +UpdateRemotePlugins +qall
}

install() {
  local cmd=$1; shift
  __inf "Installing ${cmd} requirements."
  if __asdf_owned ${cmd}; then
    ${cmd} install "$@"
  else
    __err_owned ${cmd}
  fi
}

__asdf_data_dir() {
  local data_dir

  if [ -n "${ASDF_DATA_DIR}" ]; then
    data_dir="${ASDF_DATA_DIR}"
  else
    data_dir="$HOME/.asdf"
  fi

  echo "$data_dir"
}

__os_name() {
  command cat /etc/*release | grep -w NAME | tr -d 'NAME="'
}

__os_type() {
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    printf $(__os_name)
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    printf "Darwin"
  else
    printf "Unknown"
  fi
}

__asdf_owned() {
  command which $1 | grep -q "$(__asdf_data_dir)"
}

__ls() {
  printf "\n::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n\n"
}

__inf() {
  __ls
  printf "📋 INFO\t$@\n"
  __ls
}

__err_owned() {
  __ls
  printf "👺 ERR\t${1} isnt asdf managed. Check your ENV.\n"
  which ${1}
  __ls
}

main "$@"

